export enum HttpErrorCode {
  NOT_FOUND = 'ERR404',
  SERVICE_UNAVAILABLE = 'ERR503',
  INTERNAL_SERVER_ERROR = 'ERR500',
  BAD_REQUEST = 'ERR400',
  CONFLICT = 'ERR409',
  UNAUTHORIZED = 'ERR401',
  FORBIDDEN = 'ERR403',
}
